# Generated by Django 3.2.25 on 2025-08-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('factory_year', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
